version: '2.2'
services:
  test_elasticsearch_9999:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      # give our test instance a port number that is for sure not going to write to some poor cluster listening on 9200
      - 9999:9200
